# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 2
NUM_WORKER_NODE = 3

IP_BASE = "192.168.5."
MASTER_IP_START = 10
WORKER_IP_START = 20
LB_IP_START = 100

HOST_PORT_BASE = 2700

# Note that for vagrant-libvirt, it would create a management network for all VM
# instances, which is attached to eth0, so the interface IPs assigned here will
# be shown as eth1's.

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "generic/ubuntu1804"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "libvirt" do |libvirt|
  #   # Customize the amount of memory on the VM:
  #   libvirt.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  # https://github.com/vagrant-libvirt/vagrant-libvirt#provider-options
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.default_prefix = "k8s-"
    libvirt.cpus = 2
    libvirt.memory = 2048
    libvirt.cpu_mode = "host-model"
  end

  #
  # Domain-specific configurations (domain: a VM defined in libvirt)
  # https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
  #
  # Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
    config.vm.define "master-#{i}" do |node|
      # Name shown in the GUI
      node.vm.hostname = "master-#{i}"
      node.vm.network :private_network,
                      :ip => IP_BASE + "#{MASTER_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22,
                      host: "#{HOST_PORT_BASE + MASTER_IP_START + i}"

      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
      node.vm.provision "setup-dns", :type => "shell", :path => "ubuntu/update-dns.sh"
      node.vm.provision "file", source: "./ubuntu/cert_verify.sh", destination: "$HOME/"
    end
  end

  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.hostname = "worker-#{i}"
      node.vm.network :private_network,
                      :ip => IP_BASE + "#{WORKER_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22,
                      host: "#{HOST_PORT_BASE + WORKER_IP_START + i}"

      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
      node.vm.provision "setup-dns", :type => "shell", :path => "ubuntu/update-dns.sh"
      node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker-2.sh"
      node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"
      node.vm.provision "file", source: "./ubuntu/cert_verify.sh", destination: "$HOME/"
    end
  end

  # Provision Load Balancer Node
  config.vm.define "loadbalancer" do |node|
    node.vm.hostname = "loadbalancer"
    node.vm.network :private_network,
                    :ip => IP_BASE + "#{LB_IP_START}"
    node.vm.network "forwarded_port", guest: 22,
                    host: "#{HOST_PORT_BASE + LB_IP_START}"

    node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh"
    node.vm.provision "setup-dns", :type => "shell", :path => "ubuntu/update-dns.sh"
  end
end
